### ISSUE TITLE
Custom resource limits for prometheus do not work as excepted

### ISSUE THREAD

**Issue by oliver-goetz** [googlecloudrobotics/core#65]
[values-cloud.yaml](https://github.com/googlecloudrobotics/core/blob/master/src/app_charts/prometheus/values-cloud.yaml#L10-L12) of prometheus app suggests that you are able to set custom resource limits during app rollout.

However, the resource limits of prometheus-kube-prometheus stateful sets remain default
```yaml
...
    spec:
      containers:
      - args:
        - --web.console.templates=/etc/prometheus/consoles
        - --web.console.libraries=/etc/prometheus/console_libraries
        - --config.file=/etc/prometheus/config_out/prometheus.env.yaml
        - --storage.tsdb.path=/prometheus
        - --storage.tsdb.retention.time=120d
        - --web.enable-lifecycle
        - --storage.tsdb.no-lockfile
        - --web.external-url=https://www.endpoints.sap-asimov-ogoetz.cloud.goog/prometheus/
        - --web.route-prefix=/
        image: quay.io/prometheus/prometheus:v2.13.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /-/healthy
            port: web
            scheme: HTTP
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        name: prometheus
        ports:
        - containerPort: 9090
          name: web
          protocol: TCP
        readinessProbe:
          failureThreshold: 120
          httpGet:
            path: /-/ready
            port: web
            scheme: HTTP
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 200m
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 2Gi
...
```

even when using an app rollout like this

```yaml
apiVersion: apps.cloudrobotics.com/v1alpha1
kind: AppRollout
metadata:
  labels:
    app: prometheus
  name: prometheus
spec:
  appName: prometheus-dev
  cloud:
    limits:
      cpu: "2000m"
      memory: "12Gi"
  robots:
  - selector:
      matchLabels:
        model: mir100
```

Changing values in [values-cloud.yaml](https://github.com/googlecloudrobotics/core/blob/master/src/app_charts/prometheus/values-cloud.yaml#L10-L12) before deployment changes the resource limits.
