### ISSUE TITLE
Update on StatefulSets fails when updating serviceName

### ISSUE THREAD

**Issue by oliver-goetz** [googlecloudrobotics/core#66]
Chartassignment controller fails when trying to update `serviceName` attribute of a StateFulSet.
The error message suggests that it will fail on updates of other attributes too.
Deleting and recreating the StateFulSet would fix the issue, but there is a side effect. Update could destroy the state if the StateFulSet defines objects like PVCs.

Status of corresponding chartassigment
```yaml
status:
  conditions:
  - lastTransitionTime: "2021-04-06T10:00:14Z"
    lastUpdateTime: "2021-04-06T10:00:36Z"
    message: '1/8 resources failed to apply: apps/v1/StatefulSet/app-ewm-robot-controller/robot-controller-karis01:
      apply patch: StatefulSet.apps "robot-controller-karis01" is invalid: spec: Forbidden:
      updates to statefulset spec for fields other than ''replicas'', ''template'',
      and ''updateStrategy'' are forbidden'
    status: "False"
    type: Settled
  - lastTransitionTime: "2021-04-06T10:00:14Z"
    lastUpdateTime: "2021-04-06T10:00:14Z"
    message: Release not settled yet
    status: "False"
    type: Ready
```
