### ISSUE TITLE
Unable to Create new CRD - "chargeactions.example.com" is invalid

### ISSUE THREAD

**Issue by jasirjasir** [googlecloudrobotics/core#91]
While trying the example **Creating a declarative API** , Getting the error `The CustomResourceDefinition "chargeactions.example.com" is invalid: spec.versions[0].schema.openAPIV3Schema: Required value: schemas are required` . This error occurred while deploying the   **charge-crd.yaml** file . Anyone faced similar issue?

**Comment by ensonic** [comment]
Thanks a lot for reporting this. I think we need to change:
https://github.com/googlecloudrobotics/core/blob/master/docs/how-to/examples/charge-service/charge-crd.yaml#L7
to add at least:
```yaml
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
```
Alternatively we need to actually define the schema here. You can find examples if you look at the other crds in the repo (e.g. run: `git grep CustomResourceDefinition *.yaml`.

Could you test this suggestion and if it works, send a PR?
